[project]
name = "example"
version = "0.1.0"
description = "Example FastAPI application using fastapi-vite-assets"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "fastapi-vite-assets",
]

[tool.uv.sources]
fastapi-vite-assets = { workspace = true }
